@AuthExample_HostAddress = https://localhost:7054
@the_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJlZ3VsYXItdXNlciIsInN1YiI6InJlZ3VsYXItdXNlciIsImp0aSI6IjljMmVhMDBkIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NDEwMDkiLCJodHRwczovL2xvY2FsaG9zdDo0NDMxMCIsImh0dHA6Ly9sb2NhbGhvc3Q6NTEzNyIsImh0dHBzOi8vbG9jYWxob3N0OjcwNTQiXSwibmJmIjoxNzI3MDkwMzIyLCJleHAiOjE3MzQ5NTI3MjIsImlhdCI6MTcyNzA5MDMyMywiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.YlxEuQw7yRGqyAhuKNTekNyafJ-kwX-Vwv0gcZJkHHY
@the_admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlNoaW1vIiwic3ViIjoiU2hpbW8iLCJqdGkiOiI2YjhjYjhmIiwicm9sZSI6ImFkbWluIiwidXNlclR5cGUiOiJ1c2VydHlwZTIiLCJlbWFpbCI6InNoaW1vbmRAYW55LXRlY2hzLmNvLmlsIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NDEwMDkiLCJodHRwczovL2xvY2FsaG9zdDo0NDMxMCIsImh0dHA6Ly9sb2NhbGhvc3Q6NTEzNyIsImh0dHBzOi8vbG9jYWxob3N0OjcwNTQiXSwibmJmIjoxNzI3MDkxNjE4LCJleHAiOjE3MzQ5NTQwMTgsImlhdCI6MTcyNzA5MTYxOSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.wsH9ritOcaeyLP2GOPJGyttXOEC_FlBNIPZp_ZAwTGI

GET {{AuthExample_HostAddress}}/wow/
Accept: application/json
Authorization: Bearer {{the_admin_token}}

###

GET {{AuthExample_HostAddress}}/auth
Accept: application/json
Authorization: Bearer {{the_admin_token}}

###
