global using API.Apis;
global using API.Extensions;
global using API.Infrastructure;
global using API.Interfaces;
global using API.Model.Dtos;
global using API.Model.Entities;
global using API.Services;
global using AutoMapper;
global using Microsoft.EntityFrameworkCore;
