global using API.Apis;
global using API.Extensions;
global using API.Infrastructure;
global using API.Interfaces;
global using API.Model.Dtos;
global using API.Model.Entities;
global using API.Services;
global using AutoMapper;
global using Microsoft.EntityFrameworkCore;
global using API.Exceptions;
global using Microsoft.AspNetCore.Diagnostics;
global using System.Net;
global using API.ExceptionHandlers;
global using API.Mapping;
global using API.OpenAPI;
global using Asp.Versioning;
global using Asp.Versioning.Builder;
global using Asp.Versioning.Conventions;

